[profile.default]
src = 'src'
lib = 'lib'
test = 'test'
script = 'script'
out = 'out'
cache_path  = 'cache'
extra_output = ['storageLayout']

ffi = true
ast = true
build_info = true
optimizer = true

# fs permissions for deployment (false by default)
fs_permissions = [
    { access = "read", path = "out" },
    { access = "read-write", path = "deployment" }
]

# fuzzing options
[fuzz]
runs = 100

# invariant options
[invariant]
runs = 20

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
