[profile.default]
src = 'src'
lib = 'lib'
test = 'test'
script = 'script'
out = 'out'
cache_path = 'cache'

# required by upgradability
# see: https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# forces recompilation, required by Upgradable contracts
force = true

# fs permissions for deployment (false by default)
fs_permissions = [
    { access = "read", path = "out" },
    { access = "read-write", path = "deployments" },
]

# fuzzing options
[fuzz]
runs = 100

# invariant options
[invariant]
runs = 20

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
