[profile.default]
src = 'contracts'
lib = 'lib'
test = 'test'
script = 'scripts'
out = 'out'
cache_path  = 'cache'
ffi = true
ast = true
build_info = true
optimizer = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read", path = "out" }, { access = "write", path = "deployment" }]
remappings = [
"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
